<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\Tenant;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Public-facing invoice page — what the QR code on the invoice resolves to.
 *
 * URL: /i/{invoiceId}?expires=...&signature=...
 *
 * Same security model as PublicReceiptController: HMAC-signed, expiring URL.
 * Default TTL is 30 days. The link is generated by InvoiceController and
 * embedded into the printed invoice PDF.
 *
 * All Eloquent reads use withoutTenant() because this route runs outside any
 * authenticated tenant context — without it the BelongsToTenant global scope
 * filters every result to the (null) current tenant and 404s.
 */
class PublicInvoiceController extends Controller
{
    public function show(Request $request, string $invoiceId): Response
    {
        if (! $request->hasValidSignature()) {
            abort(403, 'invalid or expired invoice link');
        }

        $invoice = Invoice::withoutTenant()->find($invoiceId);
        if (! $invoice) {
            abort(404);
        }

        $tenant = Tenant::find($invoice->tenant_id);
        $customer = $invoice->customer_id
            ? Customer::withoutTenant()->find($invoice->customer_id)
            : null;
        $items = InvoiceItem::withoutTenant()
            ->where('invoice_id', $invoice->id)
            ->get();

        if (! $tenant || ! $customer) {
            abort(404);
        }

        return response()->view('invoices.public', [
            'invoice' => $invoice,
            'items' => $items,
            'customer' => $customer,
            'tenant' => $tenant,
            'qrSvg' => null,
            'publicUrl' => null,
            'isPublicWeb' => true,
        ]);
    }
}
